In [2]:
from ctypes import *
import numpy as np
from tqdm import tqdm
import time

In [3]:
libc_matmul32 = CDLL("/home/dyu/Dropbox/tf-notebooks/cuda_comp/mat_mul_example/using_dll/matmul_kernel.so")
matmul32 = libc_matmul32.MatMul

libc_matmul_cublas = CDLL("/home/dyu/Dropbox/tf-notebooks/cuda_comp/mat_mul_example/using_dll/matmul_cublas.so")
matmul_cublas = libc_matmul_cublas.MatMul_cuBLAS

In [4]:
matmul32.restype = None
matmul32.argtypes = (POINTER(c_double), POINTER(c_double),
                     POINTER(c_double), POINTER(c_int))

matmul_cublas.restype = None
matmul_cublas.argtypes = (POINTER(c_double), POINTER(c_double),
                          POINTER(c_double), POINTER(c_int))

In [5]:
import numpy.random

In [6]:
np.random.seed(2022)
A = np.random.randn(5,5)
B = np.random.randn(5,5)
C = np.zeros_like(A)

In [7]:
N = A.shape[0]
N2 = N**2
N_c = c_int(N)

A_cr = (c_double * N2)(*A.ravel(order='C'))
B_cr = (c_double * N2)(*B.ravel(order='C'))

res = np.zeros_like(A)
res_cr = (c_double * N2)(*res.ravel(order='C'))

t1 = time.time()
matmul32(A_cr, B_cr, res_cr, N_c)
t2 = time.time()

res = np.array(list(res_cr)).reshape(N,N, order = "C")
t2-t1


0.14182019233703613

In [8]:
np.matmul(A,B)

array([[ 1.9589208 , -0.18495395, -1.90480098,  1.20211442,  3.54212188],
       [ 1.38979071,  0.30167196,  1.18776044, -0.93654327,  0.61556178],
       [-3.29132559,  0.49356196,  5.73128561,  2.95903904, -7.89527645],
       [ 0.96189151, -1.75245935, -1.24470423,  0.06135214,  3.61120848],
       [-3.12120937, -1.93551906,  0.15948521,  0.90546154,  1.6629438 ]])

In [9]:
res

array([[ 1.9589208 , -0.18495395, -1.90480098,  1.20211442,  3.54212188],
       [ 1.38979071,  0.30167196,  1.18776044, -0.93654327,  0.61556178],
       [-3.29132559,  0.49356196,  5.73128561,  2.95903904, -7.89527645],
       [ 0.96189151, -1.75245935, -1.24470423,  0.06135214,  3.61120848],
       [-3.12120937, -1.93551906,  0.15948521,  0.90546154,  1.6629438 ]])

In [10]:
#list(zip(A_c,B_c))

In [11]:
A_cc = (c_double * N2)(*A.ravel(order='F'))
B_cc = (c_double * N2)(*B.ravel(order='F'))

res = np.zeros_like(A)
res_cc = (c_double * N2)(*res.ravel(order='F'))

t1 = time.time()
matmul_cublas(A_cc, B_cc, res_cc, N_c)
t2 = time.time()

res_cublas = np.array(list(res_cc)).reshape(N,N, order = "F")
t2-t1


0.2296292781829834

In [12]:
#list(zip(A_c,B_c))

In [13]:
res_cublas

array([[ 1.9589208 , -0.18495395, -1.90480098,  1.20211442,  3.54212188],
       [ 1.38979071,  0.30167196,  1.18776044, -0.93654327,  0.61556178],
       [-3.29132559,  0.49356196,  5.73128561,  2.95903904, -7.89527645],
       [ 0.96189151, -1.75245935, -1.24470423,  0.06135214,  3.61120848],
       [-3.12120937, -1.93551906,  0.15948521,  0.90546154,  1.6629438 ]])

In [14]:
import os
#os.getcwd()
os.listdir()

['MatMul_Example1_float.ipynb',
 'matmul_kernel_f.so',
 'matmul_cuda_float.cu',
 '.ipynb_checkpoints',
 'MatMul_Example1.ipynb',
 'matmul_kernel.so',
 'matmul_cublas.so',
 'matmul_cuda.cu',
 'matmul_cublas_float.cu',
 'old',
 'matmul_cublas.cu',
 'matmul_cublas_f.so']

In [15]:
import numpy as np

np.random.seed(2022)
A = np.random.randn(5,5)
B = np.random.randn(5,5)

lib_matmul = CDLL("./matmul_kernel.so")
matmul_ker = lib_matmul.MatMul

matmul_ker.restype = None
matmul_ker.argtypes = (POINTER(c_double), POINTER(c_double),
                       POINTER(c_double), POINTER(c_int))

n = A.shape[0]
nsq = n**2
n_c = c_int(n)

A_cr = (c_double * nsq)(*A.ravel(order='C'))
B_cr = (c_double * nsq)(*B.ravel(order='C'))

C = np.zeros_like(A)
C_cr = (c_double * nsq)(*C.ravel(order='C'))

matmul32(A_cr, B_cr, C_cr, n_c)

C = np.array(C_cr).reshape(n,n, order = "C")


In [16]:
C

array([[ 1.9589208 , -0.18495395, -1.90480098,  1.20211442,  3.54212188],
       [ 1.38979071,  0.30167196,  1.18776044, -0.93654327,  0.61556178],
       [-3.29132559,  0.49356196,  5.73128561,  2.95903904, -7.89527645],
       [ 0.96189151, -1.75245935, -1.24470423,  0.06135214,  3.61120848],
       [-3.12120937, -1.93551906,  0.15948521,  0.90546154,  1.6629438 ]])

In [40]:
C_cr

In [41]:
C_cr[0:10]

[1.9589207985462411,
 -0.18495394619847472,
 -1.9048009770738679,
 1.2021144201521272,
 3.54212187899325,
 1.3897907092212443,
 0.3016719595183009,
 1.1877604426849977,
 -0.9365432683503286,
 0.6155617759705471]

## Numerical Comparison

In [43]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
from ctypes import *
import numpy as np
import time

libc_matmul32 = CDLL("/home/dyu/Dropbox/tf-notebooks/cuda_comp/mat_mul_example/using_dll/matmul_kernel.so")
matmul32 = libc_matmul32.MatMul

libc_matmul_cublas = CDLL("/home/dyu/Dropbox/tf-notebooks/cuda_comp/mat_mul_example/using_dll/matmul_cublas.so")
matmul_cublas = libc_matmul_cublas.MatMul_cuBLAS

matmul32.restype = None
matmul32.argtypes = (POINTER(c_double), POINTER(c_double),
                     POINTER(c_double), POINTER(c_int))

matmul_cublas.restype = None
matmul_cublas.argtypes = (POINTER(c_double), POINTER(c_double),
                          POINTER(c_double), POINTER(c_int))

np.random.seed(2022)
n = 2500
A = np.random.randn(n,n).astype(np.float64)
B = np.random.randn(n,n).astype(np.float64)
niter = 11
comp_time_ker = np.zeros(niter)
comp_time_blas = np.zeros(niter)

for i in np.arange(niter):
    n_int = c_int(n)
    
    # kernel
    A_ra = A.ctypes.data_as(POINTER(c_double))
    B_ra = B.ctypes.data_as(POINTER(c_double))

    C = np.zeros_like(A)
    C_ra = C.ctypes.data_as(POINTER(c_double))

    t1 = time.time()
    matmul32(A_ra, B_ra, C_ra, n_int)
    t2 = time.time()
    comp_time_ker[i] = t2-t1
    
    
    # cublas
    A_c = A.ravel(order='F')
    A_ca = A_c.ctypes.data_as(POINTER(c_double))
    B_c = B.ravel(order='F')
    B_ca = B_c.ctypes.data_as(POINTER(c_double))

    C_c = np.zeros_like(A).ravel(order='F')
    C_ca = C_c.ctypes.data_as(POINTER(c_double))

    t1 = time.time()
    matmul_cublas(A_ca, B_ca, C_ca, n_int)
    t2 = time.time()
    comp_time_blas[i] = t2-t1
    
    print('\n ',i+1,'-th iteration, Collapsed Time: ', comp_time_ker[i], ',  ', comp_time_blas[i],
          ', Total: ',comp_time_ker[i]+comp_time_blas[i])
    



  1 -th iteration, Collapsed Time:  0.3050234317779541 ,   0.2974860668182373 , Total:  0.6025094985961914

  2 -th iteration, Collapsed Time:  0.14057016372680664 ,   0.11767077445983887 , Total:  0.2582409381866455

  3 -th iteration, Collapsed Time:  0.14240121841430664 ,   0.12072324752807617 , Total:  0.2631244659423828

  4 -th iteration, Collapsed Time:  0.14037013053894043 ,   0.10969948768615723 , Total:  0.25006961822509766

  5 -th iteration, Collapsed Time:  0.14217925071716309 ,   0.11232423782348633 , Total:  0.2545034885406494

  6 -th iteration, Collapsed Time:  0.14081525802612305 ,   0.11555075645446777 , Total:  0.2563660144805908

  7 -th iteration, Collapsed Time:  0.1406104564666748 ,   0.11308979988098145 , Total:  0.25370025634765625

  8 -th iteration, Collapsed Time:  0.1404714584350586 ,   0.10933113098144531 , Total:  0.2498025894165039

  9 -th iteration, Collapsed Time:  0.14280915260314941 ,   0.11237478256225586 , Total:  0.2551839351654053

  10 -th it

In [2]:
np.round(np.mean(comp_time_ker[1:]),4), np.round(np.mean(comp_time_blas[1:]),4)

(0.1411, 0.1134)

In [5]:
0.1444-0.1153

0.0291